apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yml -o k8s/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: go-app
  name: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: go-app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.prod.yml -o k8s/
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: go-app
    spec:
      containers:
        - env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  key: DB_URL
                  name: go-app-env-prod
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  key: ENV
                  name: go-app-env-prod
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  key: HOST
                  name: go-app-env-prod
            - name: MINIO_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  key: MINIO_ACCESS_KEY_ID
                  name: go-app-env-prod
            - name: MINIO_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  key: MINIO_BUCKET_NAME
                  name: go-app-env-prod
            - name: MINIO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: MINIO_ENDPOINT
                  name: go-app-env-prod
            - name: MINIO_PUBLIC_URL_BASE
              valueFrom:
                configMapKeyRef:
                  key: MINIO_PUBLIC_URL_BASE
                  name: go-app-env-prod
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MINIO_ROOT_PASSWORD
                  name: go-app-env-prod
            - name: MINIO_ROOT_USER
              valueFrom:
                configMapKeyRef:
                  key: MINIO_ROOT_USER
                  name: go-app-env-prod
            - name: MINIO_SECRET_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  key: MINIO_SECRET_ACCESS_KEY
                  name: go-app-env-prod
            - name: MINIO_USE_SSL
              valueFrom:
                configMapKeyRef:
                  key: MINIO_USE_SSL
                  name: go-app-env-prod
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: go-app-env-prod
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: go-app-env-prod
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: go-app-env-prod
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: go-app-env-prod
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: go-app-env-prod
          image: dukunuu/go-app
          name: go-app
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: registry
      restartPolicy: Always
