apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.prod.yml -o k8s/
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: postgres-db
  name: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.prod.yml -o k8s/
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: postgres-db
    spec:
      containers:
        - env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  key: DB_URL
                  name: postgres-db-env-prod
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  key: ENV
                  name: postgres-db-env-prod
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  key: HOST
                  name: postgres-db-env-prod
            - name: MINIO_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  key: MINIO_ACCESS_KEY_ID
                  name: postgres-db-env-prod
            - name: MINIO_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  key: MINIO_BUCKET_NAME
                  name: postgres-db-env-prod
            - name: MINIO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: MINIO_ENDPOINT
                  name: postgres-db-env-prod
            - name: MINIO_PUBLIC_URL_BASE
              valueFrom:
                configMapKeyRef:
                  key: MINIO_PUBLIC_URL_BASE
                  name: postgres-db-env-prod
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MINIO_ROOT_PASSWORD
                  name: postgres-db-env-prod
            - name: MINIO_ROOT_USER
              valueFrom:
                configMapKeyRef:
                  key: MINIO_ROOT_USER
                  name: postgres-db-env-prod
            - name: MINIO_SECRET_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  key: MINIO_SECRET_ACCESS_KEY
                  name: postgres-db-env-prod
            - name: MINIO_USE_SSL
              valueFrom:
                configMapKeyRef:
                  key: MINIO_USE_SSL
                  name: postgres-db-env-prod
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: postgres-db-env-prod
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: postgres-db-env-prod
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgres-db-env-prod
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: postgres-db-env-prod
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: postgres-db-env-prod
          image: postgres:15-alpine
          livenessProbe:
            exec:
              command:
                - pg_isready -U app_user -d app_db
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 10
          name: postgres-db-prod
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-data-prod
      restartPolicy: Always
      volumes:
        - name: db-data-prod
          persistentVolumeClaim:
            claimName: db-data-prod
